### ISSUE TITLE
AutoDetectVersion method throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by RameshBabuPrudhvi** [selcukes/selcukes-java#2]
java.lang.IndexOutOfBoundsException: Index: 82, Size: 82
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at io.github.selcukes.wdb.util.VersionDetector.getCompatibleBinaryVersion(VersionDetector.java:139)
	at io.github.selcukes.wdb.util.VersionDetector.getVersion(VersionDetector.java:60)
	at io.github.selcukes.wdb.core.ChromeBinary.browserVersion(ChromeBinary.java:77)
	at io.github.selcukes.wdb.WebDriverBinary$Builder.autoDetectVersion(WebDriverBinary.java:93)
	at io.github.selcukes.tests.WebDriverBinaryTest.autoDetectBrowserVersionTest(WebDriverBinaryTest.java:120)

**Comment by RameshBabuPrudhvi** [comment]
Fixed
